In [2]:
import numpy as np 
class Perceptron:

    def __init__(self, learning_rate=0.008, n_iters=1000, activation = 'tanh'):
        self.lr = learning_rate
        self.n_iters = n_iters
        self.activation = activation

        self.weights = None
        self.bias = None

    def fit(self, X, y):
        n_samples, n_features = X.shape

        # init parameters
        self.weights = np.zeros(n_features)
        self.bias = 0

        y_ = np.array([1 if i > 0 else 0 for i in y])

        for _ in range(self.n_iters):
            
            for idx, x_i in enumerate(X):

                linear_output = np.dot(x_i, self.weights) + self.bias
                y_predicted = self.activation_func(linear_output)
                
                # Perceptron update rule
                update = self.lr * (y_[idx] - y_predicted)

                self.weights += update * x_i
                self.bias += update

    def predict(self, X):
        linear_output = np.dot(X, self.weights) + self.bias
        y_predicted = self.activation_func(linear_output)
        return y_predicted

    def activation_func(self, x):
        if self.activation == 'tanh':
            out = (np.exp(2*x) - 1) / (np.exp(2*x) + 1) 
            return np.where(out >=0, 1, 0)
        elif self.activation == 'step':
            return np.where(x>=0, 1, 0)
        elif self.activation == 'sigmoid':
            out = 1 / (1 + np.exp(-x))
            return np.where(x>=0.5 ,1, 0)

In [4]:
def accuracy(y_true, y_pred):
    accuracy = np.sum(y_true == y_pred) / len(y_true)
    return accuracy

In [3]:
# importing libraries 

from sklearn.metrics import classification_report
from random import shuffle
import warnings 
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import random
from random import randint
import pandas as pd

In [5]:
url = 'https://raw.githubusercontent.com/nsethi31/Kaggle-Data-Credit-Card-Fraud-Detection/master/creditcard.csv'
df = pd.read_csv(url)     
df.head()

   Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

**Balanced Sample**

In [6]:
index_0 = df.index[df['Class'] == 1]
random.seed(10)
# generating 2000 ranodm numbers between 0 and 2000

index_1 = [randint(0,20000) for p in range(0,4000)]

final_index = list(set(index_0).union(set(index_1))) 
print('final_index_length' , len(final_index))
print('class1 length ', len(index_0))

modified_df = df.iloc[final_index]
modified_df.head()

final_index_length 4085
class1 length  492

          Time        V1        V2        V3  ...       V27       V28  Amount  Class
16390  27768.0 -1.262125  1.148266  1.699716  ... -0.131393  0.014240   21.00      0
16391  27768.0 -1.262125  1.148266  1.699716  ... -0.131393  0.014240   21.00      0
11        10.0  0.384978  0.616109 -0.874300  ...  0.042472 -0.054337    9.99      0
16396  27772.0  1.311626  0.075634 -1.292619  ... -0.021801  0.023605    1.79      0
16397  27772.0 -9.048871  3.917282 -6.845208  ...  0.232505 -0.110212   99.99      0

[5 rows x 31 columns]

**MOdel 1**

In [8]:
X = modified_df.drop('Class', axis = 1)
y = modified_df.Class

X_train,X_test, y_train,y_test = train_test_split(X,y, test_size = 0.3, random_state = 9)

model1 = Perceptron(activation = 'step')
model1.fit(np.array(X_train), np.array(y_train))
y_preds = model1.predict(X_test)  
print(accuracy(y_test, y_preds))
print(classification_report(y_test, y_preds))
print(confusion_matrix(y_test, y_preds))

0.8768352365415987
              precision    recall  f1-score   support

           0       0.88      1.00      0.93      1074
           1       1.00      0.01      0.01       152

    accuracy                           0.88      1226
   macro avg       0.94      0.50      0.47      1226
weighted avg       0.89      0.88      0.82      1226

[[1074    0]
 [ 151    1]]